services:
  - type: web
    name: contact-manager
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Foct5J9KvFYAYSTQXVH0Og8NJP0aBKvR1++IhD+XnjQ=
      - key: APP_NAME
        value: Contact Manager
      - key: APP_URL
        value: https://contact-manager-78x4.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d190enh5pdvs73dqdddg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: contact_manager_db_vrp1
      - key: DB_USERNAME
        value: samuel
      - key: DB_PASSWORD
        value: ykG5mAxwTpodbV8mxRnko9gxiDP0XaCN
    ports:
      - port: 80
        targetPort: 80

databases:
  - name: contact-db
    databaseName: contact_manager_db_vrp1
    user: samuel
    plan: free
