services:
  - type: web
    name: contact-manager
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:TsvGEovbDYwxpY14aZVPiLFET+YWDrMOOUjXU76iYVA=
      - key: APP_URL
        value: https://contact-manager-kklb.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d190enh5pdvs73dqdddg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: contact_manager_db_vrp1
      - key: DB_USERNAME
        value: samuel
      - key: DB_PASSWORD
        value: ykG5mAxwTpodbV8mxRnko9gxiDP0XaCN
